version: '3.8'

services:
  test-module:
    build:
      context: .
      dockerfile: test-module/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - redis

  mvc-module:
    build:
      context: .
      dockerfile: mvc-module/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - redis

  webflux-module:
    build:
      context: .
      dockerfile: webflux-module/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
