server:
  port: 8080

spring:
  data:
    redis:
      host: redis
      port: 6379
  websocket:
    allowed-origins: "*"

app:
  mvc-url: http://mvc-module:8081/topics/test/subscribe
  webflux-url: http://webflux-module:8082/topics/test/subscribe
