server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  websocket:
    allowed-origins: "*"

app:
  mvc-url: http://localhost:8081/topics/test/subscribe
  webflux-url: http://localhost:8082/topics/test/subscribe
